lints.workspace = true

[package]
name = "slot-arithmetic"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
derive_more = { version = "2.0.1", features = ["add", "display", "from", "mul"] }
hex.workspace = true
minicbor = { workspace = true, features = ["std", "half", "derive"] }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
