[package]
name = "amaru-stores"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
amaru-ledger = { path = "../ledger" }
rocksdb.workspace = true
tracing.workspace = true
pallas-codec.workspace = true
hex.workspace = true
