[package]
name = "amaru-ouroboros"
version = "0.1.0"
edition = "2021"

[dependencies]
hex.workspace = true
kes-summed-ed25519.workspace = true
mockall.workspace = true
pallas-codec.workspace = true
pallas-crypto.workspace = true
pallas-math.workspace = true
pallas-network.workspace = true
pallas-primitives.workspace = true
pallas-traverse.workspace = true
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
vrf_dalek.workspace = true

[dev-dependencies]
ctor.workspace = true
insta = { workspace = true, features = ["yaml"] }
mockall.workspace = true
pallas-traverse.workspace = true
tracing-subscriber.workspace = true
criterion.workspace = true
rand.workspace = true
serde_json.workspace = true

[[bench]]
harness = false
name = "benchmark"
