[package]
name = "amaru-stores"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true

[dependencies]
hex.workspace = true
pallas-codec.workspace = true
rocksdb.workspace = true
tracing.workspace = true

iter-borrow.workspace = true
amaru-kernel.workspace = true
amaru-ledger.workspace = true

[dev-dependencies]
proptest.workspace = true
