# Find the full list of available options here: https://doc.rust-lang.org/cargo/reference/config.html

[alias]
acfmt = "fmt --all -- --check"
aclippy = "clippy --workspace --all-targets --all-features -- -D warnings"
atest = "test --workspace --all-targets --all-features "