# Find the full list of available options here: https://doc.rust-lang.org/cargo/reference/config.html

[alias]
fmt-amaru = "fmt --all -- --check"
clippy-amaru = "clippy --workspace --all-targets --all-features -- -D warnings"
test-amaru = "test --workspace --all-features"