name: CI Build and Test

on:
  workflow_dispatch:
    inputs:
      network:
        description: Network to run
        type: choice
        options: [preprod, preview]
        required: false
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, converted_to_draft, ready_for_review]
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always
  RUST_NIGHTLY_TOOLCHAIN: nightly-2026-08-03
  RUSTUP_LOG: error

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs: {}
