name: Coding Practices

on:
  workflow_dispatch:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - "crates/**/Cargo.toml"
      - "crates/**/Cargo.lock"
      - "examples/**/Cargo.toml"
      - "examples/**/Cargo.lock"

jobs:
  unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: bnjbvr/cargo-machete
          tag: v0.7.0
          binaries-location: cargo-machete-v0.7.0-x86_64-unknown-linux-musl
      - run: cargo-machete

  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: EmbarkStudios/cargo-deny
          tag: 0.16.4
          binaries-location: cargo-deny-0.16.4-x86_64-unknown-linux-musl
      - run: cargo deny-amaru

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: ${{ env.RUST_CACHE_PATH }}
          key: cargo-x86_64-unknown-linux-gnu
          restore-keys: |
            cargo-x86_64-unknown-linux-gnu
      - run: cargo clippy-amaru

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt-amaru
